---
- name: Install nvim in macOS
  community.general.homebrew:
    name:
      - neovim
    state: present
  when: ansible_distribution == "MacOSX"

- name: Install vim-plug on macos
  shell:
    cmd: sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  when: ansible_distribution == "MacOSX"

- name: Install treesitter parsers
  shell:
    cmd: nvim --headless -c 'TSInstallSync! {{ parsers | join(" ") }}' -c quit
  vars:
    parsers:
      - typescript
      - javascript
      - tsx
      - html
      - yaml
      - toml
      - json
      - jsonc
      - python
      - jsdoc
      - lua
      - bash
      - vim
      - scss
      - astro
      - markdown
      - markdown_inline
  changed_when: false
