# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # Breadcrumb
  - trigger: ":bc"
    replace: "[[{{yesterdaybc}}|<< Yesterday]] | [[{{tomorrowbc}}|Tomorrow >>]]"
    vars:
      - name: yesterdaybc
        type: shell
        params:
          cmd: "bash -c 'LC_ALL=en_GB date +%Y-%m-%d_%a -d -1day'"
      - name: tomorrowbc
        type: shell
        params:
          cmd: "bash -c 'LC_ALL=en_GB date +%Y-%m-%d_%a -d +1day'"

  # Meeting
  - trigger: ":meet"
    word: true
    replace: |
             ## Meeting
             - Tags:
             Attendees:
             Tasks:
             Notes:

  
