# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Dates
  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d.%m.%Y"

  - trigger: ":isodate"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"

  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  # Breadcrumb 
  - trigger: ":bc"
    replace: "[[Work/Daily Notes/{{yesterdaybc}}|<< Yesterday]] | [[Work/Daily Notes/{{tomorrowbc}}|Tomorrow >>]]"
    vars:
      - name: yesterdaybc
        type: shell
        params:
          cmd: "bash -c 'LC_ALL=en_GB date +%Y-%m-%d_%a -d -1day'"
      - name: tomorrowbc
        type: shell
        params:
          cmd: "bash -c 'LC_ALL=en_GB date +%Y-%m-%d_%a -d +1day'"
          
  - trigger: ":nwbc"
    replace: "[[Work/Daily Notes/{{yesterdaybc}}|<< Yesterday]] | [[Work/Daily Notes/{{tomorrowbc}}|Next Week >>]]"
    vars:
      - name: yesterdaybc
        type: shell
        params:
          cmd: "bash -c 'LC_ALL=en_GB date +%Y-%m-%d_%a -d -1day'"
      - name: tomorrowbc
        type: shell
        params:
          cmd: "bash -c 'LC_ALL=en_GB date +%Y-%m-%d_%a -d +3day'"
          
  - trigger: ":lwbc"
    replace: "[[Work/Daily Notes/{{yesterdaybc}}|<< Last Week]] | [[Work/Daily Notes/{{tomorrowbc}}|Tomorrow >>]]"
    vars:
      - name: yesterdaybc
        type: shell
        params:
          cmd: "bash -c 'LC_ALL=en_GB date +%Y-%m-%d_%a -d -3day'"
      - name: tomorrowbc
        type: shell
        params:
          cmd: "bash -c 'LC_ALL=en_GB date +%Y-%m-%d_%a -d +1day'"
          

  # Meeting
  - trigger: ":meet"
    word: true
    replace: |
             ### Meeting XYZ
             - Tags:
             Attendees:
             Goal:
             Tasks:
             Notes:

  
