#!/bin/bash
GITCONFIG=$HOME/.gitconfig
GITCONFIG_LOCAL=$HOME/.gitconfig.local
DOTFILES=`readlink -f $PWD/..`
DF_GITCONFIG=$DOTFILES/.gitconfig
DF_GITCONFIG_LOCAL_DEFAULT=$DOTFILES/.gitconfig.local.default

FISH_CONFIG=$HOME/.config/fish/config.fish
DF_FISH_ALIASES=$DOTFILES/aliases.fish
DF_FISH_CONFIG=$DOTFILES/config.fish

VIMRC=$HOME/.vimrc
DF_VIMRC=$DOTFILES/.vimrc

LATEXMKRC=$HOME/.latexmkrc
DF_LATEXMKRC=$DOTFILES/.latexmkrc

ESPANSO=$HOME/.config/espanso/default.yml
DF_ESPANSO=$DOTFILES/espanso-default.yml

read -n 1 -p "Do you want to link ~/.gitconfig to ./.gitconfig? [Y/n]"
echo
if [[ $REPLY =~ ^[yY]?$ ]]; then
    doLink=true
    if [ -f $GITCONFIG ]; then
        doLink=false
        read -n 1 -p "$GITCONFIG already exists. Do you want to override it? [y/N]"
        echo
        if [[ $REPLY =~ ^[yY]?$ ]]; then
            doLink=true
        fi
    fi
    
    if $doLink; then
        ln -f -s $DF_GITCONFIG $GITCONFIG
        echo "Linked gitconfig"
        read -n 1 -p "Do you want to add a default ~/.gitconfig.local? [Y/n]" 
        echo
        if [[ $REPLY =~ ^[yY]?$ ]]; then
            cp -f $DF_GITCONFIG_LOCAL_DEFAULT $GITCONFIG_LOCAL
            echo "Copied $DF_GITCONFIG_LOCAL_DEFAULT to $GITCONFIG_LOCAL"
            echo "Remeber to change the gpgsigningkey"
        fi    
    fi
fi

read -n 1 -p "Do you want to include the dotfiles fish conifg in your local fish conifg? [Y/n]"
echo
if [[ $REPLY =~ ^[yY]?$ ]]; then
    echo ". $DF_FISH_ALIASES" >> $FISH_CONFIG
    echo ". $DF_FISH_CONFIG" >> $FISH_CONFIG
    echo "Appended two lines to $FISH_CONFIG"
fi


read -n 1 -p "Do you want to link ~/.vimrc to ./.vimrc? [Y/n]"
echo
if [[ $REPLY =~ ^[yY]?$ ]]; then
    doLink=true
    if [ -f $VIMRC ]; then
        doLink=false
        read -n 1 -p "$VIMRC already exists. Do you want to override it? [y/N]"
        echo
        if [[ $REPLY =~ ^[yY]?$ ]]; then
            doLink=true
        fi
    fi
    
    if $doLink; then
        ln -f -s $DF_VIMRC $VIMRC
        echo "Linked vimrc" 
    fi
fi


read -n 1 -p "Do you want to link ~/.latexmkrc to ./.latexmkrc? [Y/n]"
echo
if [[ $REPLY =~ ^[yY]?$ ]]; then
    doLink=true
    if [ -f $LATEXMKRC ]; then
        doLink=false
        read -n 1 -p "$LATEXMKRC already exists. Do you want to override it? [y/N]"
        echo
        if [[ $REPLY =~ ^[yY]?$ ]]; then
            doLink=true
        fi
    fi
    
    if $doLink; then
        ln -f -s $DF_LATEXMKRC $LATEXMKRC
        echo "Linked latexmkrc" 
    fi
fi

read -n 1 -p "Do you want to link ~/.config/espanso/default.yml to ./espanso-default.yml? [Y/n]"
echo
if [[ $REPLY =~ ^[yY]?$ ]]; then
    doLink=true
    if [ -f $ESPANSO ]; then
        doLink=false
        read -n 1 -p "$ESPANSO already exists. Do you want to override it? [y/N]"
        echo
        if [[ $REPLY =~ ^[yY]?$ ]]; then
            doLink=true
        fi
    fi
    
    if $doLink; then
        ln -f -s $DF_ESPANSO $ESPANSO
        echo "Linked latexmkrc" 
    fi
fi
