---
- name: Install Node.js in macOS
  community.general.homebrew:
    name:
      - node
    state: present
  when: ansible_distribution == "MacOSX"

- name: Ensure npm global prefix is configured
  lineinfile:
    path: "{{ ansible_env.HOME }}/.npmrc"
    line: "prefix={{ npm_config_prefix }}"
    state: present
    create: true

- name: Install global packages
  loop:
    - volta
    - npm-merge-driver
  community.general.npm:
    name: "{{ item }}"
    state: present
    global: true
